#### Dependencies
dependencies = [
  "Intl.DateTimeFormat"
]

#### Specification Link
spec = "https://tc39.es/ecma402/#sec-initializedatetimeformat"

#### Documentation Link
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat#using_options"

#### License
license = "MIT"

#### Notes
notes = [
  "See formatjs documentation for more info on 'golden' vs 'all' timezones. https://formatjs.io/docs/polyfills/intl-datetimeformat"
]

#### Browser compatibility
[browsers]
android = "<4.4"
ie = "9 - *"
ie_mob = "9 - *"
firefox = "<52"
opera = "<15"
chrome = "<24"
safari = "<10"
ios_saf = "<10"
firefox_mob = "<52"
samsung_mob = "<1.5"

[install]
module = "@formatjs/intl-datetimeformat"
paths = [ "/add-all-tz.js" ]
clean = [
  "polyfill.js",
]
