dependencies = [
	"_ArrayIterator",
	"Symbol.iterator",
	"DOMTokenList",
	"Element.prototype.classList"
]

license = "MIT"
spec = "https://dom.spec.whatwg.org/#domtokenlist"

[browsers]
edge = "<16"
edge_mob = "<16"
ie = "9 - 12"
ie_mob = "9 - 12"
safari = "<10.1"
chrome = "<50"
firefox = "<50"
ios_saf = "10.3"
opera = "<50"
samsung_mob = "<5"
bb = "10 - *"
