aliases = [ "es6", "es2015" ]
dependencies = [ "_ESAbstract.CreateMethodProperty" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/tanh"
spec = "https://tc39.github.io/ecma262/#sec-math.tanh"

[browsers]
android = "<5"
bb = "*"
chrome = "<38"
edge = "<12"
edge_mob = "<12"
firefox = "<25"
ie = "*"
ie_mob = "10 - *"
ios_chr = "*"
ios_saf = "4 - 6.1"
opera = "10 - 20"
op_mob = "*"
op_mini = "*"
firefox_mob = "<25"

