dependencies = [ "DOMTokenList" ]
license = "MIT"
spec = "https://dom.spec.whatwg.org/#domtokenlist"

[browsers]
android = "<81"
edge = "<18"
firefox = "<61"
ie = "*"
ios_saf = "<12"
op_mob = "*"
opera = "<54"
safari = "<12"
samsung_mob = "<9"
