aliases = [ "default-3.4", "default-3.5", "default-3.6", "default" ]
dependencies = [ ]

[browsers]
chrome = "<29"
firefox = "<21"
firefox_mob = "<21"
ie = "6 - 10"
ie_mob = "10"
safari = "<7"
ios_saf = "<7"
