aliases = [
	"es5",
	"modernizr:es5object",
	"default-3.5",
	"default-3.6",
	"default",
	"blissfuljs"
]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToPropertyKey",
	"_ESAbstract.Type",
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor"

[browsers]
firefox = "<36"
safari = "<10"
ios_saf = "<10"
firefox_mob = "<36"
ie = "*"
android = "*"
edge = "<14"
chrome = "<45"
