dependencies = [ "Object.defineProperty" ]
notes = [ ]
spec = "http://www.w3.org/TR/screen-orientation/"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation"

[browsers]
edge = "<79"
edge_mob = "*"
ie = "9 - *"
ie_mob = "*"
firefox = "<30"
chrome = "<49"
safari = "*"
ios_saf = "*"
opera = "<25"
op_mob = "*"
android = "<5"
bb = "*"
firefox_mob = "<30"
