dependencies = [ ]
license = "MIT"
spec = "https://tc39.github.io/ecma402/2016/"
repo = "https://github.com/andyearnshaw/Intl.js"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl"
notes = [
  "Locales must be specified separately by prefixing the locale name with `Intl.~locale`, eg `Intl.~locale.en-GB`."
]

[browsers]
chrome = "<71"
edge = "<18"
firefox = "<51"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "<58"
safari = "<11"
ios_saf = "<11"
android = "<7.1"
samsung_mob = "<7"

[build]
minify = false

[install]
module = "intl"
paths = [ "dist/Intl.min.js" ]
postinstall = "update.task.js"

