dependencies = [
	"fetch",
	"Object.getOwnPropertyDescriptor",
	"Object.setPrototypeOf",
	"Event",
	"Map",
	"Symbol",
	"Symbol.toStringTag",
	"WeakMap"
]
license = "MIT"
spec = "https://dom.spec.whatwg.org/#interface-abortcontroller"
repo = "https://github.com/mysticatea/abort-controller"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/AbortController"

[browsers]
edge = "<16"
edge_mob = "*"
ie = ">=10"
ie_mob = ">=10"
firefox = "2 - 56"
opera = "10 - 52"
safari = "<12.1"
chrome = "4 - 65"
ios_saf = "<12.2"
firefox_mob = "<64"
samsung_mob = "*"
android = "*"

[install]
module = "abort-controller"
paths = [ "dist/abort-controller.umd.js" ]
