dependencies = [
	"Element.prototype.matches",
	"Map",
	"MutationObserver",
	"Node.prototype.contains",
	"Set",
	"WeakMap"
]
aliases = [
	# Polyfill was first created as "Element.prototype.inert" but the actual feature only exists on "HTMLElement"
	# https://github.com/WICG/inert/issues/181
	"Element.prototype.inert"
]
license = "W3C"
spec = "https://html.spec.whatwg.org/multipage/interaction.html#dom-inert"
repo = "https://github.com/WICG/inert"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert"

[browsers]
android = "<102"
bb = "*"
chrome = "<102"
edge = "<102"
edge_mob = "<102"
firefox = "<104"
firefox_mob = "<104"
ie = "9 - *"
ie_mob = "9 - *"
ios_chr = "*"
ios_saf = "<15.5"
op_mini = "*"
op_mob = "<70"
opera = "<88"
safari = "<15.5"
samsung_mob = "*"
