aliases = [ ]
dependencies = [ "IntersectionObserver", "Object.defineProperty" ]
docs = "https://github.com/w3c/IntersectionObserver/blob/master/explainer.md"
spec = "http://rawgit.com/w3c/IntersectionObserver/master/index.html"
notes = [ ]
repo = "https://github.com/w3c/IntersectionObserver"

[browsers]
android = "<51"
bb = "*"
chrome = "< 51"
edge = "< 16"
edge_mob = "< 16"
firefox = "< 55"
firefox_mob = "< 55"
ie = "*"
ie_mob = "*"
ios_saf = "< 12.2"
op_mini = "*"
op_mob = "< 46"
opera = "< 45"
safari = "< 12.1"
samsung_mob = "< 7"