#### Aliases
# An alias is another name for the polyfill that can be used when requesting a bundle.
# For example, the alias `es5` is used to replicate an ECMAScript 5 environment.
aliases = ['es2021']

#### Dependencies
# List any web platform features that you use in your polyfill.
# For example:
# dependencies = [
#    "Object.defineProperty"
# ]
dependencies = [
    "_ESAbstract.Call",
    "_ESAbstract.CreateMethodProperty",
    "_ESAbstract.Get",
    "_ESAbstract.GetMethod",
    "_ESAbstract.GetSubstitution",
    "_ESAbstract.IsCallable",
    "_ESAbstract.IsRegExp",
    "_ESAbstract.RequireObjectCoercible",
    "_ESAbstract.StringIndexOf",
    "_ESAbstract.ToString",
    "RegExp.prototype.flags",
    "Symbol.replace"
]

#### Specification Link
# The url which is where the specification for the feature exists.
# For example the specification for String.prototype.replaceAll is https://tc39.es/ecma262/#sec-string.prototype.replaceall
spec = "https://tc39.es/ecma262/#sec-string.prototype.replaceall"

#### Documentation Link
# The url which is where the documentation for the feature exists, this is usually a link to MDN.
# For example the documentation for String.prototype.replaceAll is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll"

#### License
# The license this code has been given. All code authored within the polyfill-library itself is MIT.
# Third-party code can use any license which is listed on https://opensource.org/licenses
license = "MIT"

#### Browser compatibility
# List what browsers require the polyfill.
# You can check the related Mozilla Developer Network (MDN) page for the compatibility, they also have their browser compatibility data on GitHub.
# For example: [MDN nextElementSibling browser support](https://github.com/mdn/browser-compat-data/blob/master/api/NonDocumentTypeChildNode.json#L99-L149)
# Browsers that can be listed:
# - android
# - bb
# - chrome
# - edge
# - edge_mob
# - firefox
# - ios_chr
# - ios_saf
# - ie
# - ie_mob
# - opera
# - op_mini
# - safari
# - firefox_mob
# - samsung_mob
# The browser list uses a form of semantic versioning to indicate which browser requires polyfilling.
# If all versions of a browser require the polyfill you can use the wildcard asterisk (*):
# For specific versions you can specify a number, for example if a polyfill is required in Internet Explorer 8 and below you can use "<9"
[browsers]
chrome = "50 - 84"
edge = "79 - 84"
edge_mob = "79 - 84"
firefox = "49 - 76"
ios_chr = "10 - 13.3"
ios_saf = "10 - 13.3"
opera = "37 - 70"
safari = "10 - 13"
samsung_mob = ">=5"
