aliases = []
dependencies = []
spec = "https://html.spec.whatwg.org/multipage/forms.html#dom-form-requestsubmit-dev"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit"
license = "MIT"

[browsers]
android = "<76"
chrome = "<76"
edge = "<79"
firefox = "<75"
firefox_mob = "<79"
ie = "*"
ie_mob = "*"
opera = "<63"
op_mob = "<64"
op_mini = "*"
safari = "<16"
ios_saf = "<16"
samsung_mob = "<12"
