dependencies = [ "_ArrayIterator", "Symbol.iterator" ]
license = "MIT"
spec = "https://dom.spec.whatwg.org/#nodelist"

[browsers]
edge = "<16"
edge_mob = "<16"
ie = "9 - *"
ie_mob = "9 - *"
safari = "<10"
chrome = "<51"
firefox = "<50"
ios_saf = "<10"
opera = "<50"
samsung_mob = "<5"
bb = "10 - *"

