aliases = [ "es6", "es2015" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.OrdinaryCreateFromConstructor",
	"_ESAbstract.Get",
	"_ESAbstract.IsCallable",
	"_ESAbstract.GetIterator",
	"_ESAbstract.IteratorStep",
	"_ESAbstract.IteratorValue",
	"_ESAbstract.Call",
	"_ESAbstract.IteratorClose",
	"_ESAbstract.IsArray",
	"_ESAbstract.Type",
	"_ESAbstract.SameValueZero",
	"Symbol"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet"
license = "MIT"

[browsers]
android = "*"
bb = "10 - *"
chrome = "<44"
firefox = "<40"
firefox_mob = "<34"
ie = ">=7"
ie_mob = ">=10"
opera = "<25"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<4"
