aliases = []
dependencies = [ ]
spec = "https://www.w3.org/TR/geometry-1/#DOMRect"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/DOMRect"

[browsers]
ie = ">=9"
ie_mob = ">=9"
chrome = "<61"
safari = "<10.1"
ios_saf = "<10.1"
firefox = "<31"
firefox_mob = "<31"
android = "*"
edge = "<79"
samsung_mob = "<8"
opera = "<48"
op_mob = "<45"
