aliases = [ "es2021" ]
dependencies = [
	"_ESAbstract.CreateDataPropertyOrThrow",
	"_ESAbstract.IterableToList",
]
license = "MIT"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError"

[browsers]
android = "*"
bb = "*"
chrome = "<85"
edge = "<85"
edge_mob = "<85"
firefox = "<79"
firefox_mob = "<79"
ie = "*"
ie_mob = "*"
opera = "*"
op_mini = "*"
safari = "<14"
ios_saf = "<14"
samsung_mob = "<14"
