dependencies = [
	"Element.prototype.matches",
	"Map",
	"MutationObserver",
	"Node.prototype.contains",
	"Set",
	"WeakMap"
]
license = "W3C"
spec = "https://html.spec.whatwg.org/multipage/interaction.html#inert"
repo = "https://github.com/WICG/inert"
docs = "https://github.com/WICG/inert/blob/master/explainer.md"

[browsers]
android = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = ">=9"
ie_mob = ">=9"
opera = "*"
op_mob = "*"
safari = "*"
ios_saf = "*"
