dependencies = [ ]
license = "MIT"
spec = "https://tc39.github.io/ecma262/#sec-string.prototype.normalize"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize"

[browsers]
android = "<5"
bb = "*"
chrome = "<34"
firefox = "<31"
firefox_mob = "<31"
ie = "*"
ie_mob = "*"
ios_saf = "<10"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "<10"
samsung_mob = "<2"

[install]
module = "unorm"
paths = [ "lib/unorm.js" ]
postinstall = "update.task.js"
