docs = "https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate"
repo = "https://github.com/YuzuJS/setImmediate"

[browsers]
chrome = "*"
firefox = "*"
opera = "*"
safari = "*"
ie = "<10"
ios_saf = "*"
android = "*"
op_mob = "*"
ie_mob = "<10"
firefox_mob = "*"
bb = "*"
op_mini = "*"
samsung_mob = "*"
