name: Lint
on:
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run lint
