aliases = [
	"Intl",
	"Intl.DateTimeFormat.prototype.formatToParts"
]
dependencies = [
	"Array.isArray",
	"Array.prototype.filter",
	"Array.prototype.indexOf",
	"Array.prototype.lastIndexOf",
	"Array.prototype.map",
	"Array.prototype.reduce",
	"Date.now",
	"Intl.getCanonicalLocales",
	"Intl.Locale",
	"Intl.NumberFormat",
	"Object.assign",
	"Object.create",
	"Object.keys",
	"Object.setPrototypeOf",
	"Set",
	"WeakMap"
]
license = "MIT"
spec = "https://tc39.es/ecma402/#datetimeformat-objects"
repo = "https://github.com/formatjs/formatjs/tree/master/packages/intl-datetimeformat"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat"
notes = [
	"Locales must be specified separately by prefixing the locale name with `Intl.DateTimeFormat.~locale`, eg `Intl.DateTimeFormat.~locale.en-GB`."
]

# Browser compatibility list for Int.DateTimeFormat.~timeZone.all and Int.DateTimeFormat.~timeZone.golden must match this one, update both if a change is needed here.
[browsers]
android = "*"
ie = "9 - *"
ie_mob = "9 - *"
edge = "<79"
edge_mob = "<79"
firefox = "*"
opera = "*"
chrome = "<76"
safari = "*"
ios_saf = "*"
firefox_mob = "*"
samsung_mob = "*"

[install]
module = "@formatjs/intl-datetimeformat"
paths = [ "polyfill.iife.js" ]
postinstall = "update.task.js"
clean = [
	"~locale",
	"polyfill.js",
]
